export const Roles = {
  OPERADOR_PDE: process.env.OPERADOR_PDE!,
  ADMIN_PDE: process.env.ADMIN_PDE!,
  ADMINISTRADOR_EMPRESA: process.env.ADMINISTRADOR_EMPRESA!,
  SUPER_ADMIN_EMPRESA: process.env.SUPER_ADMIN_EMPRESA!,
  SOPORTE_APLICATIVO: process.env.SOPORTE_APLICATIVO!,
  SUPER_ADMIN_APLICATIVO: process.env.SUPER_ADMIN_APLICATIVO!,
  OWNER_APLICATIVO: process.env.OWNER_APLICATIVO!,
}